### ISSUE TITLE
Errors if unicode in Job output

### ISSUE THREAD

**Issue by ValentinFunk** [deis/dockerbuilder#49]
When the Dockerfile produces Unicode output (i believe npm install prints a check sign or something) I get this error:

```
Traceback (most recent call last):
  File "/deploy.py", line 106, in <module>
    log_output(stream, True)
  File "/deploy.py", line 25, in log_output
    print(stream_chunk.replace('\n', ''))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 264-266: ordinal not in range(128)
size of streamed logs 2173
Waiting for the deis/dockerbuild-valued-quadrant-febcad02-8068a452 pod to end. Checking every 100ms for 15m0s
Done
remote: 2016/04/19 17:09:05 Error running git receive hook [Build pod exited with code 1, stopping build.]
Checking for builder pod exit code
To ssh://git@deis.10.2.47.19.xip.io:2222/valued-quadrant.git
   d9c7b3a..febcad0  1.3 -> 1.3
```

I believe it is this line:
https://github.com/deis/dockerbuilder/blob/60662962262e9088ce6bf6697c9e89493076b8d1/rootfs/deploy.py#L25

DEBUG is 1

**Comment by bacongobbler** [comment]
more info from slack:

```
[16:33:48] 
Traceback (most recent call last):
  File "/deploy.py", line 102, in <module>
    log_output(stream, True)
  File "/deploy.py", line 21, in log_output
    print(stream_chunk.replace('\n', ''))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

9:37 AM
my guess it’s the funky ascii “art” that gulp does for me
9:37 AM

[16:30:23] Tasks for /data/build/gulpfile.build.js
[16:30:23] ├── build-pre
```

**Comment by helgi** [comment]
Whatever the fix is for this I'd want to get it backported to Controller, could be worth it to update to docker-py and use `decode=true` like we do in the Controller? https://github.com/deis/controller/blob/master/rootfs/registry/dockerclient.py#L135-L154 (also look at the push command)

**Comment by iartem** [comment]
+1: 

```
Traceback (most recent call last):
  File "/deploy.py", line 106, in <module>
    log_output(stream, True)
  File "/deploy.py", line 25, in log_output
    print(stream_chunk.replace('\n', ''))
remote: 2016/05/06 13:22:41 Error running git receive hook [Build pod exited with code 1, stopping build.]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 803: ordinal not in range(128)
```

Good old deis also had similar issue: https://github.com/deis/deis/issues/4420

**Comment by jchauncey** [comment]
moving to rc1

**Comment by bacongobbler** [comment]
this is a pretty big issue, and I'd say is a showstopper for releasing rc1 since users cannot deploy their dockerfile apps.

@smothiki or @kmala do either of you have time to take a look into this?
